### ISSUE TITLE
Disable Page Select

### ISSUE THREAD

**Issue by sco0ts** [HASwitchPlate/HASPone#107]
Is there any way to remove Page Select at the bottom? Wanting to create an always shown single page of buttons

**Comment by aderusha** [comment]
The page layouts are defined in the [HMI project file](https://github.com/HASwitchPlate/HASPone/blob/main/Nextion_HMI/HASwitchPlate.HMI).  You'd have to edit that project with the [Nextion editor](https://nextion.tech/nextion-editor/), then flash to your display.  Once you've done so, be aware that some blueprints which expect to make use of the default HMI may no longer work, depending on the scope of the changes you make to the project.
