### ISSUE TITLE
Info about Temp sensor

### ISSUE THREAD

**Issue by mattthhdp** [HASwitchPlate/HASPone#110]
Since we can define a PIR sensor, is it possible to also add the DHT library, so we can use pin D0 or D1 for a DHT22 for example ?

**Comment by aderusha** [comment]
In general, I'm staying away from making the HASPone into a sensor platform in addition to a control surface.  The PIR code was an experiment to try solutions for detecting if a person was in front of the screen which never really panned out well as I never really found a sensor that I could package safely into the project enclosure.

Of course, the code is open and anyone is welcome to modify for their own use, but I likely won't be developing or accepting PRs for sensor integration unless there is some direct tie-in to the control function.

Fortunately, there are a lot of projects out there that can integrate just about anything you throw at them, ESPhome and Tasmota come to mind as great solutions with good support under Home Assistant!
