### ISSUE TITLE
Media player P8

### ISSUE THREAD

**Issue by mattthhdp** [HASwitchPlate/HASPone#130]
is it possible to replace the slider with 3 button (like to row above) because the slider trigger when you release the button. It's pretty hard to set the volume.

with 3 button it will be easier to press volume up or down a couple of time and mute.

**Comment by aderusha** [comment]
Possible, yes - but not without some significant changes to the project.  You'd have to re-design the Nextion HMI project and then update any blueprints to match.  [This document](https://github.com/HASwitchPlate/HASPone/wiki/Modifying-HASPone-to-work-with-other-Nextion-screens) explains a bit about the process there.
