### ISSUE TITLE
Crash on Wifi Connect

### ISSUE THREAD

**Issue by 0xJoeMartin** [HASwitchPlate/HASPone#137]
I have built a HASP and uploaded the Arduino sketch.  I am getting the HASP Wifi Setup screen on the Nextion but when I connect to the "HASwitchPlate" SSID, the ESP crashes and restarts.  Serial Monitor output:

================================================================================
[+0.071s] SYSTEM: Starting HASwitchPlate v1.02
[+0.076s] SYSTEM: Last reset reason: Fatal exception:3 flag:2 (Exception) epc1:0x4000bf64 epc2:0x00000000 epc3:0x00000000 excvaddr:0x40285469 depc:0x00000000
[+0.090s] SYSTEM: heapFree: 30992 heapMaxFreeBlockSize: 30896
Crash information recovered from EEPROM
Crash # 1 at 4660 ms
Restart reason: 2
Exception cause: 3
epc1=0x4000bf64 epc2=0x00000000 epc3=0x00000000 excvaddr=0x40285469 depc=0x00000000
>>>stack>>>
3ffff900: 3fff7014 00000ca0 00000000 00000000 
3ffff910: 40285469 0000000b 3ffff960 00000000 
3ffff920: 00000000 3ffffb60 3ffff99c 402221ab 
3ffff930: 00000000 3fff535c 3ffff960 4022c140 
3ffff940: 3ffff960 3ffffc98 3ffffb60 4022c169 
3ffff950: 3ffffc60 3ffffc98 3ffffb60 402270ee 
3ffff960: 3fff6854 000b000f 80000000 00000030 
3ffff970: 00004bc6 00000000 00000000 00000000 
3ffff980: 0024002f 00000000 00000000 6567412d 
3ffff990: 3fff5944 3fff5a08 00000000 3fff7014 
3ffff9a0: 0ca00caf 80000000 00000000 00000000 
3ffff9b0: 3ffffc60 00000001 3fff192c 40239080 
3ffff9c0: 00000000 00000000 00000000 401000e9 
3ffff9d0: 00000000 4bc6a7f0 00000000 40203271 
3ffff9e0: 00000000 3fff5944 3fff58fc 40205e8e 
3ffff9f0: 00000000 3ffffc60 40100989 00000000 
3ffffa00: 0000103f 00000000 00000000 00000001 
3ffffa10: 00000000 00000000 3fff58fc 00000000 
3ffffa20: 3ffffc60 3fff5920 3fff58fc 40207d7e 
3ffffa30: 40239eb4 00000000 00001388 40237447 
3ffffa40: 00000000 00000000 3fff6df4 00000000 
3ffffa50: 3ffffc60 3ffffc60 3ffffb60 40227bc8 
3ffffa60: 3ffffc60 00000001 3ffffb60 40223f23 
3ffffa70: 00000000 00000000 00000001 40100874 
3ffffa80: 3ffffc60 00000020 3ffffb60 00000000 
3ffffa90: 3ffffc60 00000001 3ffffb60 00000000 
3ffffaa0: 3ffffc60 00000001 3ffffb60 40227ef4 
3ffffab0: 00000000 000b000f 00000000 00000000 
3ffffac0: 73646e6f 00000000 00000000 000b000f 
3ffffad0: 00000000 40101500 40101500 
Incomplete stack trace saved!
<<<stack<<<
No more EEPROM space available to save crash information!
================================================================================

[+0.292s] SPIFFS: mounting SPIFFS
[+0.327s] SPIFFS: [WARNING] /config.json not found, will be created on first config save
[+0.335s] HMI: Waiting for LCD connection
[+0.582s] HMI IN: [7 bytes]: 0xff 0x00 0x00 0x00 0xff 0xff 0xff
[+0.588s] HMI: Querying LCD backlight status
[+0.593s] HMI OUT: get dim
[+0.596s] HMI IN: [4 bytes]: 0x88 0xff 0xff 0xff
[+0.601s] HMI: Nextion panel connected.
[+0.697s] HMI IN: [5 bytes]: 0x66 0x00 0xff 0xff 0xff
[+0.703s] HMI IN: [sendme Page] '0'
[+0.706s] HMI IN: [8 bytes]: 0x71 0x64 0x00 0x00 0x00 0xff 0xff 0xff
[+0.713s] HMI IN: [Int Return] '100'
[+0.716s] HMI IN: lcdBacklightDim '100'
[+0.721s] HMI OUT: bkcmd=3
[+0.724s] HMI: Querying LCD firmware version number
[+0.730s] HMI OUT: get p[0].b[2].val
[+0.734s] HMI IN: [8 bytes]: 0x71 0x02 0x00 0x00 0x00 0xff 0xff 0xff
[+0.740s] HMI IN: [Int Return] '2'
[+0.743s] HMI IN: lcdVersion '2'
[+0.747s] HMI: Querying LCD model information
[+0.752s] HMI OUT: con⸮ect
[+0.759s] HMI IN: [69 bytes]: 0x63 0x6f 0x6d 0x6f 0x6b 0x20 0x31 0x2c 0x33 0x30 0x36 0x30 0x31 0x2d 0x30 0x2c 0x4e 0x58 0x33 0x32 0x32 0x34 0x54 0x30 0x32 0x34 0x5f 0x30 0x31 0x31 0x52 0x2c 0x31 0x34 0x31 0x2c 0x36 0x31 0x34 0x38 0x38 0x2c 0x44 0x45 0x36 0x30 0x31 0x43 0x46 0x34 0x32 0x33 0x34 0x46 0x33 0x33 0x32 0x35 0x2c 0x34 0x31 0x39 0x34 0x33 0x30 0x34 0xff 0xff 0xff
[+0.814s] HMI IN: nextionModel: NX3224T024_011R
[+0.820s] HMI OUT: 'p[0].b[1].font=6'
[+2.764s] WIFI: Failed to connect to assigned AP, entering config mode
[+2.772s] HMI OUT: 'p[0].b[1].font=6'
[+2.786s] HMI OUT: 'p[0].b[1].txt=" HASP WiFi Setup\r AP: HASwitchPlate\rPassword: hasplate\r\r\r\r\r\r\r  httpr//1;2.168.4.1"'
[+2.840s] HMI OUT: vis 3,1

**Comment by aderusha** [comment]
@0xJoeMartin - is this issue still present?  Did wiping and reflashing resolve the problem?

**Comment by aderusha** [comment]
Closing the issue after 4 weeks.
