### ISSUE TITLE
Stuck on wifi connected

### ISSUE THREAD

**Issue by scubieman** [HASwitchPlate/HASPone#173]
I use to have the old haswitchplate installed on my HA. Now trying to upgrade to HASPone.

My device keeps getting stuck on WIFI connected. I tried factory resetting. Double checking names. And nothing is working. I can see if it Blueprint as device. Any ideas what issue is?

**Comment by aderusha** [comment]
OK so first, make sure you [go through this process to clear out the old HASP stuff](https://github.com/HASwitchPlate/HASPone/wiki/Updating-legacy-HASP-to-HASPone).  If you're still not connecting (or things just aren't working out right for you in general), [grab a debug log](https://github.com/HASwitchPlate/HASPone/wiki/Capture-HASPone-debug-output) and post it here, then we can work through what is happening on your device and hopefully get you moving.

**Comment by scubieman** [comment]
How would i delete switch plates added to HA accidently? Or Change the name? Example if i had plate01, and I switched name to brplate. It will show plate01 and brplate in list.

**Comment by aderusha** [comment]
In Home Assistant, go to Configuration > Devices & Services > Devices tab > find the old device (plate01) and click on it > Delete.

**Comment by scubieman** [comment]
okay they connect to wifi , but stuck on "wifi connected" and dont do anything useful

**Comment by aderusha** [comment]
Allright, can you post a debug dump of the whole process?  Is this device currently in the wall?

**Comment by scubieman** [comment]
its sitting next to me. I have two of them, I can not access the ip address. Generally what works is unplugging a bunch of times, but i still have some issues
want to chat on DRzz discord?

**Comment by scubieman** [comment]
@aderusha So device says wifi connecting..... However I show it active in HA now. I tried running the automation HASPone Core functionality on both devices but fails to do anything
![SpWTytIJCb](https://user-images.githubusercontent.com/42748871/148236600-ec0a1241-b16a-4924-8eb3-3bb516b4b83e.png)
.

**Comment by scubieman** [comment]
Lowered the serial speed down to 115200. It appears to be working now.
