### ISSUE TITLE
Trouble locating small quantities of threaded inserts and screws

### ISSUE THREAD

**Issue by rkhanso** [HASwitchPlate/HASPone#206]
Yes, this is not an issue with the hardware or software of the HASPone device itself. I'm near the end of the build and am striking out finding the threaded inserts and matching screws. The Amazon link on the Github page for the threaded inserts shows they are unavailable. I've checked Fastenal and don't find any M2 inserts. They don't seem to have any standard/US sizes that small either. I'd rather not buy in bulk since I only need 4 of them.

Is there a decent alternative for the hardware or other options for assembling the case?

**Comment by aderusha** [comment]
Hey thanks for the head's up! I've gone and updated the BOM to point to suitable components which (as of this writing) are currently in stock.  [Here are the inserts you'll be needing](https://www.amazon.com/uxcell-Knurled-Threaded-Insert-Embedment/dp/B07LBQFNQD/).

Single quantities are going to be more difficult, the economics of selling small parts is such that the price of the part is a small faction of the price of selling the part (amazon fees, shipping, etc).  You might find a seller that's only selling a few of the things, but the price isn't likely to be very different as the platform/shipping/etc fees don't go much lower than whatever it already costs to ship 100 tiny brass inserts.
