### ISSUE TITLE
Firmware update issue 1.0.6

### ISSUE THREAD

**Issue by farberm** [HASwitchPlate/HASPone#247]
I update to firmware 1.06. When I tried to update the LCD I received error message not correct model? Is there a different file I should use than the one provided (HASwitchPlate.tft) with the 1.0.6 files?
HASPone FW Version: 1.06
LCD Model: NX3224F024_011R
LCD FW Version: 3
LCD Active Page: 3
LCD Serial Speed: 921600

**Comment by aderusha** [comment]
There are two firmwares in this project, the HASPone PCB is now at 1.06 and LCD firmware is version 3, so you should be good to go!
