### ISSUE TITLE
Find way, how change background color for each button on page6

### ISSUE THREAD

**Issue by proasnet** [HASwitchPlate/HASPone#31]
On page 6 I have a call of color scenes of one RGBWW light. Now, I have here a texts with colors, but, is possible change background color of each button for easy recognize color preset?
For example:
White button without text for call white scene
Red button without text for call red scene
Blue button...etc...

I Find only this blueprint:
Display Toggle
But I'm not sure if this is the right choice

Thank you

**Comment by aderusha** [comment]
Currently, the display text blueprint does not offer options for setting colors.  I'm setting this as a feature request, seems like something we could add to the blueprint!

**Comment by aderusha** [comment]
Finally updated the [Display Text blueprint](https://github.com/HASwitchPlate/HASPone/blob/main/Home_Assistant/blueprints/hasp_Display_Text.yaml) with the ability to define the 4 color values manually or to use the current theme settings.

[![Display Text](https://my.home-assistant.io/badges/blueprint_import.svg)](https://my.home-assistant.io/redirect/blueprint_import/?blueprint_url=https%3A%2F%2Fgithub.com%2FHASwitchPlate%2FHASPone%2Fblob%2Fmain%2FHome_Assistant%2Fblueprints%2Fhasp_Display_Text.yaml)

**Comment by aderusha** [comment]
I've additionally published the [Apply Theme blueprint](https://github.com/HASwitchPlate/HASPone/blob/main/Home_Assistant/blueprints/hasp_Apply_Theme.yaml) which will allow setting theme colors to any buttons which don't have a blueprint handling that already.

[![Apply Theme](https://my.home-assistant.io/badges/blueprint_import.svg)](https://my.home-assistant.io/redirect/blueprint_import/?blueprint_url=https%3A%2F%2Fgithub.com%2FHASwitchPlate%2FHASPone%2Fblob%2Fmain%2FHome_Assistant%2Fblueprints%2Fhasp_Apply_Theme.yaml)
