### ISSUE TITLE
Good tip for quick light

### ISSUE THREAD

**Issue by proasnet** [HASwitchPlate/HASPone#32]
I tested idea for quick light in room. Instead of a motion sensor, I connected a capacitive sensor TTP223 to the D1, located under the HASP cover next to the display. My wife really appreciated that when she enters the room just for a little thing, she doesn't have to look for the command to light up on the display.
Very nice and simple. Good helper on white strong light !!!

**Comment by aderusha** [comment]
One note - this should probably be over in [Discussions](https://github.com/HASwitchPlate/HASPone/discussions).  But I still want to see pictures, this sounds perfect :D

**Comment by proasnet** [comment]
Thank you. Is very easy. I am sory for prototype looking, as you see, I have an enhanced version of Nextion and next him is touch sensor with TTP223

![hasp](https://user-images.githubusercontent.com/76579362/110482621-274c9e00-80e9-11eb-90b1-35baa1405a52.jpg)

**Comment by aderusha** [comment]
I'm going to close this as it's not really an issue w/ the project (but still a great idea!). Thanks for the tip :D
