### ISSUE TITLE
Iddle not working

### ISSUE THREAD

**Issue by proasnet** [HASwitchPlate/HASPone#33]
Hi, my next problem is, that iddle blueprint not working on all HASPOne devices.
I have a scorlling page in basic for all, as 1 page as basic. In Iddle, I have a page 1 after 30 sec.
Not working.
Thank you for help.

![obrázok](https://user-images.githubusercontent.com/76579362/110608703-c5457480-818c-11eb-99c4-4c8a79d97589.png)

**Comment by aderusha** [comment]
Any chance you can post a debug log showing the behavior?

**Comment by proasnet** [comment]
You mean a telnet log from any hasp? Or from?

Dne čt 11. 3. 2021 16:14 uživatel Allen Derusha ***@***.***>
napsal:

**Comment by jhhernan** [comment]
@aderusha I think that is a typo. Check the quotation mark at the end of line 127 in the hasp_Activate_Page_on_Idle.yaml file.

**Comment by aderusha** [comment]
Well that's a dumb bug, I think you nailed it @jhhernan !  Just fixed the blueprint, re-import and you should be ready to go @proasnet !

**Comment by jhhernan** [comment]
Thanks @aderusha . I don't know where to comment this, so excuse me. Please check the font size of the hasp_Display_Calendar_with_Icon.yaml (line 138). Using font size 9 the text overlays with the icon.

**Comment by aderusha** [comment]
Another great catch @jhhernan!  I'll get it sorted out.  

I think you'll find [the Discussions link above](https://github.com/HASwitchPlate/HASPone/discussions) is a good place for comments in general.

**Comment by jhhernan** [comment]
I having some trouble with this automation. It is working as expected, but it continues refreshing/"repainting" the selected page every period of inactivity. What can I check?

**Comment by aderusha** [comment]
The best way to help would be to provide [a debug log of the thing happening](https://github.com/HASwitchPlate/HASPone/wiki/Capture-HASPone-debug-output).

**Comment by jhhernan** [comment]
> The best way to help would be to provide [a debug log of the thing happening](https://github.com/HASwitchPlate/HASPone/wiki/Capture-HASPone-debug-output).



> I having some trouble with this automation. It is working as expected, but it continues refreshing/"repainting" the selected page every period of inactivity. What can I check?

Right now it is working perfectly. If I catch that behavior again I will attach the log. Thanks!

**Comment by jhhernan** [comment]
Please let me know if this are the logs that you need.
https://gist.github.com/jhhernan/01663bc767ec82b63bd5fd25c059126a
![AutomationConfiguration](https://user-images.githubusercontent.com/46280291/111332374-ba348d80-863f-11eb-82a1-055378a38a18.png)

**Comment by proasnet** [comment]
Yesterday I deleted old blueprint and new load a blueprint. Working as description, but every period is a display refreshed. See as display flash, It's not pleasant..
Do it all HASPOne in my home.

**Comment by aderusha** [comment]
Trying a different approach here, just pushed a new update to the blueprint that I think should resolve this problem (and another that I just noticed where the page change wasn't set to be retained)

**Comment by aderusha** [comment]
@proasnet how are things looking on this problem?  Did the blueprint fixes resolve your issue?

**Comment by proasnet** [comment]
Thak you. Problem is solved. Nice work.
