### ISSUE TITLE
Feature: ability to set mqttDiscoveryTopic prefix manually and override hardcoded value

### ISSUE THREAD

**Issue by scyto** [HASwitchPlate/HASPone#45]
**Issue:**
Not everyone uses the default of homeassistant topic prefix for the discovery topic (for example mine is hass-discovery so it is explcit in MQTT explorer what that topic is actually for, note other services like zwavejs2mqqt all document the use of different discovery topics).

Hass MQTT integration only allows for one instance and one discovery topic prefix across all services.

**Ask**
Allow mqttDiscoveryTopic to be optionally set via the web interface (it is ok for it be autopopulated with homeassistant or whatever)

**Other solutions I have considered**
reconfiguring all the other services I have connected to MQTT to use homeassistant

**Comment by aderusha** [comment]
Finally getting around to coding this request!  The HA discovery topic is now configurable in the web UI and changes are persisted to flash.  This feature will be in the upcoming [1.03 release](https://github.com/HASwitchPlate/HASPone/tree/1.03-HASPone-firmware).

If you want to test with the current dev release, run the web admin firmware update and paste in the following URL: `https://raw.githubusercontent.com/HASwitchPlate/HASPone/1.03-HASPone-firmware/Arduino_Sketch/HASwitchPlate.ino.d1_mini.bin`

**Comment by aderusha** [comment]
[Fix released in HASPone v1.03](https://github.com/HASwitchPlate/HASPone/discussions/146)
