### ISSUE TITLE
Multi Gang Installation

### ISSUE THREAD

**Issue by omayhemo** [HASwitchPlate/HASPone#51]
Unfortunately the included custom printed enclosure doesn't allow for mounting with-in a 2 or more gang.  The instructions also lack any detail about wiring.  Is there no ground, just neutral and line?

**Comment by aderusha** [comment]
There are [several multi-gang models available](https://github.com/HASwitchPlate/HASPone/tree/main/3D_Printable_Models), and if you don’t find a variation that fits your needs, let me know and I can probably whip something up.

You are correct on the lack of ground, there are no exposed conductive surfaces so a separate ground is not needed.

**Comment by omayhemo** [comment]
Thanks Allen,

I don't have a 3d printer.  Do you sell a 3 gang plate, with two paddles on one side, your HASPone on the other?

**Comment by aderusha** [comment]
I do! For $15 I will print and ship a custom 3 gang plate to your specification.  Send $15 to paypal@svideo.org along with the specific layout you are looking for.  If you want HASP on the left, with a Decora ("paddle") in the middle and also on the right, send me something like "HASP | Decora | Decora" so I know exactly what you're after.

**Comment by omayhemo** [comment]
Thanks Allen, Sent with note, but just in case
HASP | Decora | Decora
