### ISSUE TITLE
Bring Back Demo Pages from Old HASP Repo

### ISSUE THREAD

**Issue by IIAIronWolf** [HASwitchPlate/HASPone#62]
**Feature Request**
I'm loving the new HASPone setup. However, I do miss the preconfigured alarm panel with colored buttons. I hadn't gotten around to the using the thermostat example yet, but it looked amazing.
Creating our own pages using the button blueprints appears to be much easier than what we had to do before, but colorizing and making them as nice as your demo example does not seem easily possible just yet.

This is just a suggestion, because I love what you are doing with this and I'm glad I bought mine HASP pre-made from you! :D

**Comment by aderusha** [comment]
I think we should have most of the original demo automations covered off with blueprints, including a few variations on HVAC and a newly-update alarm panel blueprint!
