### ISSUE TITLE
Template variable warning: 'break' is undefined when rendering

### ISSUE THREAD

**Issue by Petervanoos** [HASwitchPlate/HASPone#67]
New Warning since last HA update:

2021-04-08 19:30:00 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'break' is undefined when rendering '{%- set color = namespace() -%} {%- for entity in device_entities(haspdevice) -%}
{%- if entity|regex_search("^light\..*_unselected_foreground_color(?:_\d+|)$") -%}
{%- set color.source=entity -%}
{{ break }}
{%- endif -%}
{%- endfor -%} {%- set brightness = state_attr(color.source, "brightness")|int / 255 -%} {%- set red=(state_attr(color.source, "rgb_color")[0] * brightness)|int -%} {%- set green=(state_attr(color.source, "rgb_color")[1] * brightness)|int -%} {%- set blue=(state_attr(color.source, "rgb_color")[2] * brightness)|int -%} {{ (red|bitwise_and(248)*256) + (green|bitwise_and(252)*8) + (blue|bitwise_and(248)/8)|int }}'

Is there a work around to get rid of the warning?

It seems to be a feature of release [2021.4:]
(https://www.home-assistant.io/blog/2021/04/07/release-20214/#warnings-for-undefined-variables-in-templates)

--->

Warnings for undefined variables in Templates
This feature is really cool. While technically a small improvement, it is a change that can impact you (as in “breaking”), but also, will greatly help you!

So imaging this little template: {{ my_variable }}

Previously, if my_variable would not exist in the template or system as a variable, Home Assistant would just ignore it and skip over it.

While this can be convenient, it can become problematic when it was misspelled or referring to a variable that doesn’t exist at all. For example, if you would have mistyped it: {{ my_varaible }}, you would never know something is wrong, unless you spotted it.

As of today, Home Assistant will tell you this, using a warning in the logs!

Screenshot of undefined variable warning logScreenshot of undefined variable warning log.

This helps to find templates that behave unexpectedly because the variable you thought was there, isn’t. It is quite possible you get a bunch of warnings after upgrading to this release. Fixing those warnings, really helps to improve your setup.

So, what if a variable isn’t always there, but I still want to use it? Well, you can give it a default, for example: {{ my_variable | default }}. Or even a default value (10 in this example): {{ my_variable | default(10) }}.

Please note that these are just warnings for now. We plan to replace the warning with an error as of Home Assistant 2021.10 (in October).

<---

**Comment by aderusha** [comment]
Man this was a dumb error carried over from my jinja test environment.  `break` isn't even a valid statement in bare Jinja (nor Home Assistant), and moreover, the entire construct wasn't really necessary.  I've pulled all the instances of this (176 of them!) and pushed the change to all blueprints.

Thanks for the head's up @Petervanoos !
